docs: generate usage.md and toolsets.md

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -24,3 +24,11 @@ jobs:
 
       - name: Run lint
         run: make lint
+
+      - name: Fail if there are changed files
+        run: |
+          if git diff --name-only | grep .; then
+            echo "Error: there are changed files after linting"
+            echo "Please run 'make lint' and commit the changes"
+            exit 1
+          fi
